# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    # (this is just an example, not intended to be a production configuration)
