# Generated by Django 5.0.8 on 2024-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('quanity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Oreder Pending', 'Oreder Pending'), ('Oreder Confirmed', 'Oreder Confirmed'), ('Payment Cancelled', 'Payment Cancelled'), ('Payment Failed', 'Payment Failed')], default='Oreder Pending', max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
